### PR TITLE
Try fixing readlink -f usage

### PR DESCRIPTION
**Pull request by jfbastien**
It doesn't exist on OSX. We should really just use python everywhere!

### CODE REVIEW

**Comment by jfbastien** [comment]
Looks like a bunch of other scripts use `readlink -f`. @binji how would you like to fix this? I'm not sure we care about symlinks here.

**Comment by binji** [comment]
I think I grabbed this from http://stackoverflow.com/a/1482133. Here are some answers on emulating readlink on OSX: http://stackoverflow.com/q/1055671. But perhaps just `dirname "$0"` is enough.

**Comment by jfbastien** [comment]
Yeah, saw those. I'm not sure we care about symlinks in the path, and in the end this should be Python ;-)

**Comment by binji** [comment]
OK, well this lgtm. May as well do it for the rest of the files too.

**Comment by jfbastien** [comment]
Alright, I edited the other files.

**Pull request merged**
